web/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace web.Models
{
    public class Post
    {
        [Key]
        public int PostId { get; set; }

        [Required]
        public string Text { get; set; }   

        [Required]
        [ForeignKey("TypeId")]
        public int TypeId { get; set; }
        public virtual Interest Type { get; set; }

        public DateTime DateCreated { get; set; }
        //public DateTime DateEdited { get; set; }
        
        #nullable enable
        public string? Image { get; set; }
        #nullable disable

        [NotMapped]
        public IFormFile ImageFile { get; set; }
        
        [ForeignKey("OwnerId")]
	    public string OwnerId { get; set; }
        public virtual AppUser Owner { get; set; }

        public virtual ICollection<Like> Likes { get; set; }
    }
}

web/Controllers/LikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;

namespace web.Controllers
{
    public class LikesController : Controller
    {
        private readonly ISDBContext _context;
        private readonly UserManager<AppUser> _userManager;

        public LikesController(ISDBContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // Like/Dislike
        public async Task<IActionResult> Create(int PostId)
        {
            var UserId = _userManager.GetUserId(User);

            //Like likeExists = await _context.Likes.FindAsync(UserId, PostId);
            Like likeExists = _context.Likes.Where(l => l.UserId == UserId && l.PostId == PostId).FirstOrDefault();

            if (ModelState.IsValid)
            {
                if(likeExists == null)
                {
                    Like like = new Like{ UserId = UserId, PostId = PostId };
                    _context.Add(like);
                }else
                {
                    _context.Remove(likeExists);
                }
                
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Posts");
        }
    }
}

web/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;

namespace web.Controllers
{   
    [Authorize]
    public class PostsController : Controller
    {
        private readonly ISDBContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IWebHostEnvironment _hostEnvironment;
        
        public PostsController(ISDBContext context, UserManager<AppUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _hostEnvironment = hostEnvironment;
        }
        

        // GET: Posts
        public async Task<IActionResult> Index(bool cur = false)
        {
            var uId =  _userManager.GetUserId(User);
            ViewData["CurrentUserId"] = uId;
            string wwwroot = _hostEnvironment.WebRootPath;            
            ViewData["wwwroot"] = wwwroot;
            ViewData["Title"] = "Home";

            IQueryable<Post> ISDBContext = _context.Posts
                .Include(p => p.Owner)
                .Include(p => p.Type)
                .Include(p => p.Likes)
                .OrderByDescending(p => p.DateCreated);

            if(cur){
                ViewData["Title"] = "My Posts";
               ISDBContext = ISDBContext.Where(p => p.OwnerId == uId);
            }

            return View(await ISDBContext.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Owner)
                .Include(p => p.Type)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["TypeId"] = new SelectList(_context.Interests, "InterestId", "Name");

            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Text,TypeId,ImageFile")] Post post)
        {
            if (ModelState.IsValid)
            {
                string wwwroot = _hostEnvironment.WebRootPath;

                AppUser AppUser = await _userManager.GetUserAsync(HttpContext.User);
                post.Owner = AppUser;
                post.OwnerId = AppUser.Id;
                post.DateCreated = DateTime.Now;

                if(post.ImageFile != null){
                    string fileName = Path.GetFileNameWithoutExtension(post.ImageFile.FileName);
                    string extension = Path.GetExtension(post.ImageFile.FileName);
                    post.Image = "postImage" + extension;

                }

                _context.Add(post);
                await _context.SaveChangesAsync();

                if(post.ImageFile != null){      
                    string path = Path.Combine(wwwroot,"userFiles" , post.OwnerId, post.PostId+"", post.Image);
                    Directory.CreateDirectory(Path.GetDirectoryName(path));
                    using(var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await post.ImageFile.CopyToAsync(fileStream);
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["TypeId"] = new SelectList(_context.Interests, "InterestId", "Name", post.TypeId);

            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);

            //only owner can edit
            var currentUserId = _userManager.GetUserId(User);
            if(post.OwnerId != currentUserId)
            {
                return RedirectToAction("Index", "Posts");
            }

            if (post == null)
            {
                return NotFound();
            }
            ViewData["OwnerId"] = new SelectList(_context.Users, "Id", "Id", post.OwnerId);
            ViewData["TypeId"] = new SelectList(_context.Interests, "InterestId", "Name", post.TypeId);
            
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Text,TypeId,DateCreated,Images,OwnerId")] Post post)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["OwnerId"] = new SelectList(_context.Users, "Id", "Id", post.OwnerId);
            ViewData["TypeId"] = new SelectList(_context.Interests, "InterestId", "Name", post.TypeId);
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Owner)
                .Include(p => p.Type)
                .FirstOrDefaultAsync(m => m.PostId == id);

            //only owner can delete
            var currentUserId = _userManager.GetUserId(User);
            if(post.OwnerId != currentUserId)
            {
                return RedirectToAction("Index", "Posts");
            }

            if (post == null)
            {
                return NotFound();
            }
            
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);

            if(post.Image != null){
                string wwwroot = _hostEnvironment.WebRootPath;
                string folder_path = Path.Combine(wwwroot, "userFiles", post.OwnerId, id+"");
                if (Directory.Exists(folder_path)){ 
                    Directory.Delete(folder_path, recursive: true);
                }
            }

            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostId == id);
        }
    }
}

web/Views/Posts/Create.cshtml
@model web.Models.Post

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <textarea cols="20" asp-for="Text" class="form-control"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" class ="form-control" asp-items="ViewBag.TypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" accept="image/*"/>
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Posts/Delete.cshtml
@model web.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PostId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

web/Views/Posts/Details.cshtml
@model web.Models.Post

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PostId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Posts/Edit.cshtml
@model web.Models.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PostId" />
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" class="form-control" asp-items="ViewBag.TypeId"></select>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Posts/Index.cshtml
@model IEnumerable<web.Models.Post>

@{
    var uId =  ViewData["CurrentUserId"] as string;
    string wwwroot = ViewData["wwwroot"] as string;
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Share your interest</a>
</p>
<table class="table">
    <tbody>
@foreach (var item in Model) {
        <tr>
        <td style="border-top-color:#121212;">
            <div class="container" style="width:80%; background-color:#242424; border-radius:10px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
                <div class="row" style="padding-left:0px">
                    <div class="col align-self-start" style="padding-left:0px">
                        <a href="@Url.Action("Details", "AppUsers", new { id=item.OwnerId })">
                            @{
                                string imgSrc = "";
                                if(item.Owner.profilePic != null && !item.Owner.profilePic.Equals("")){
                                    imgSrc = "userFiles/" + item.OwnerId + "/" + item.Owner.profilePic;
                                }else{
                                    imgSrc = "images/avatar.webp";
                                }
                            }
                            <img src="~/@imgSrc" style="padding:3px; width:48px; height:48px; border-radius:50%;">
                            <b>@Html.DisplayFor(modelItem => item.Owner.UserName)</b>
                        </a>
                        <span style="color:gray; font-size:70%;">@item.Type.Name</span>
                    </div>
                    <span style="margin-right:10px; margin-top:5px; color:gray; font-size:70%; float:right;">
                        Shared at @Html.DisplayFor(modelItem => item.DateCreated)
                    </span>
                </div>
                <div class="row" style="padding:0px; width:100%;">
                    @{
                        string image = item.Image;
                        if(image != null && !image.Equals("")){
                            var postImg = "userFiles/" + item.OwnerId + "/" + item.PostId + "/" + image;
                            <img src="~/@postImg" style="max-width:100%; width:100%; height:auto;">
                        }
                    }
                </div>
                <div class="row" style="background-color: #353535; word-break: break-all">
                    <p style="word-break: break-all color:white; margin-bottom:0px; margin-left:10px; margin-right:10px;">
                        @Html.DisplayFor(modelItem => item.Text)
                    </p>
                </div>
                <div class="row" style="color:#aaaaaa; font-size:90%;">
                    <div class="col" style="padding-left:5px">
                        <partial name="_LikePartial" for="@item"/>                 
                    </div>
                    <div class="col text-right">
                        @{
                            if(uId.Equals(item.OwnerId)){
                                    <a asp-action="Edit" asp-route-id="@item.PostId">Edit</a> <span>|</span>
                                    <a asp-action="Delete" asp-route-id="@item.PostId">Delete</a>
                            }
                        }
                        </div>
                </div>
            </div>
        </td>
    </tr>
}
    </tbody>
</table>

web/Views/Posts/_LikePartial.cshtml
@model web.Models.Post
@using Microsoft.AspNetCore.Identity

@inject UserManager<AppUser> UserManager

@{var uId = UserManager.GetUserId(User);}

@Html.DisplayFor(model => model.Likes.Count)
<span>
    <a href="@Url.Action("Create", "Likes", new { PostId =  Model.PostId})">
        @if(!Model.Likes.Any(l => l.UserId.Equals(uId) && l.PostId == Model.PostId)){
            <img class="like" style="height:28px; -webkit-filter: grayscale(100%);" src="@Url.Content("~/images/like.png")"> 
        }else{
            <img class="like" style="height:28px;" src="@Url.Content("~/images/like.png")"> 
        }
    </a>
</span>